# Generated by Django 5.0 on 2025-01-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='secondary_image',
        ),
    ]
