# Generated by Django 5.0 on 2025-01-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_main_image_category_secondary_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
