# Generated by Django 5.0 on 2025-01-12 00:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ByteaImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('image', models.ImageField(upload_to=None)),
                ('image_data', models.BinaryField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
