# Generated by Django 5.0 on 2025-01-25 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0005_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='',
                 max_length=255, verbose_name='name')),
                ('slug', models.SlugField(default='',
                 max_length=255, verbose_name='slug')),
                ('description', models.TextField(
                    default='', verbose_name='description')),
                ('is_highlighted', models.BooleanField(
                    default=False, verbose_name='is highlighted ?')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                 to='category.category', verbose_name='category')),
            ],
        ),
    ]
