# Generated by Django 5.0 on 2025-02-09 14:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('status', models.CharField(choices=[('P', 'PENDING'), ('C', 'CANCELED'), ('F', 'FINISHED')], default='P', max_length=1, verbose_name='status')),
                ('zip_code', models.CharField(default='', max_length=8, verbose_name='zip code')),
                ('state', models.CharField(default='', max_length=255, verbose_name='state')),
                ('city', models.CharField(default='', max_length=255, verbose_name='city')),
                ('neigborhood', models.CharField(default='', max_length=255, verbose_name='neigborhood')),
                ('street', models.CharField(default='', max_length=255, verbose_name='street')),
                ('number', models.CharField(default='', max_length=10, verbose_name='number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
