# Generated by Django 5.0 on 2025-01-31 17:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bytea_image', '0004_alter_byteaimage_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, null=True, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, null=True, verbose_name='slug')),
                ('description', models.TextField(default='', verbose_name='description')),
                ('price', models.FloatField(default=0.0, verbose_name='price')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('image', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bytea_image.byteaimage', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
